version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 99
  target-branch: development
  versioning-strategy: increase
  ignore:
  - dependency-name: html-webpack-plugin
    versions:
    - 4.5.0
    - 4.5.1
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.2
    - 11.2.3
  - dependency-name: core-js
    versions:
    - 3.8.1
    - 3.8.3
  - dependency-name: workbox-webpack-plugin
    versions:
    - 6.0.2
    - 6.1.0
  - dependency-name: webpack-cli
    versions:
    - 4.3.1
    - 4.4.0
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.3
    - 1.3.5
  - dependency-name: husky
    versions:
    - 4.3.6
    - 4.3.8
  - dependency-name: ts-loader
    versions:
    - 8.0.13
    - 8.0.14
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
  - dependency-name: webpack-bundle-analyzer
    versions:
    - 4.3.0
  - dependency-name: typescript
    versions:
    - 4.1.3
  - dependency-name: "@types/jest"
    versions:
    - 26.0.19
  - dependency-name: fork-ts-checker-webpack-plugin
    versions:
    - 6.0.8
  - dependency-name: webpack-dev-server
    versions:
    - 3.11.1
  - dependency-name: "@semantic-release/npm"
    versions:
    - 7.0.9
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
  - dependency-name: "@babel/register"
    versions:
    - 7.12.10
  - dependency-name: "@babel/preset-react"
    versions:
    - 7.12.10
  - dependency-name: css-loader
    versions:
    - 5.0.1
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.0
  - dependency-name: sass-loader
    versions:
    - 10.1.0
  - dependency-name: "@types/webpack"
    versions:
    - 4.41.25
  - dependency-name: create-react-app
    versions:
    - 4.0.1
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.12.7
  - dependency-name: "@types/react"
    versions:
    - 17.0.0
